language: crystal
dist: xenial
addons:
 snaps:
   - name: jq
     channel: latest/edge

crystal:
  - latest
  - nightly

install:
  - shards install
  - shards build

before_script:
  - export PATH=/var/lib/snapd/snap/bin/:$PATH
  - ./bin/oq -V
  - echo $PATH
  - which jq

script:
  - bin/ameba
  - crystal tool format --check
  - crystal spec --order random --error-on-warnings

after_success:
  - crystal docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs
  on:
    condition: "$TRAVIS_EVENT_TYPE != cron"
