name: oq
version: '1.0.1'
summary: A performant, and portable jq wrapper to support formats other than JSON
description: |
  A performant, and portable jq wrapper thats facilitates the consumption and output of formats other than JSON; using jq filters to transform the data.

grade: stable
confinement: strict
base: core18

apps:
  oq:
    command: bin/oq

parts:
  oq:
    source: ./
    plugin: crystal
    stage-packages:
      - jq
