name: oq
version: '1.3.2'
summary: A performant, and portable jq wrapper to support formats other than JSON
description: |
  A performant, and portable jq wrapper thats facilitates the consumption and output of formats other than JSON; using jq filters to transform the data.

contact: george@dietrich.app
issues: https://github.com/Blacksmoke16/oq/issues
website: https://github.com/Blacksmoke16/oq
license: MIT

grade: stable
confinement: strict
base: core18

apps:
  oq:
    command: bin/oq
    plugs:
      - home
      - removable-media

parts:
  oq:
    plugin: crystal
    crystal-build-options:
      - --release
      - --no-debug
      - '--link-flags=-s -Wl,-z,relro,-z,now'
    source: ./
    stage-packages:
      - jq
