name: oq
version: '1.2.1'
summary: A performant, and portable jq wrapper to support formats other than JSON
description: |
  A performant, and portable jq wrapper thats facilitates the consumption and output of formats other than JSON; using jq filters to transform the data.

grade: stable
confinement: strict
base: core18

apps:
  oq:
    command: bin/oq
    plugs:
      - home
      - removable-media

parts:
  oq:
    plugin: crystal
    crystal-build-options:
      - '--release'
    source: ./
    stage-packages:
      - jq
